deployment:
  name: devops-final-project
  replicaCount: 1
image:
  account: 891377304789.dkr.ecr.ap-south-2.amazonaws.com
  tag: 1
  containerPort: 3000
service:
  type: ClusterIP
  clusterIPPort: 3000
resource:
  cpu:
    requests: 0.1
    limit: 0.2
  memory:
    requests: 200Mi
    limit: 300Mi
environment:
  env: DEV
namespace: dev
